### ISSUE TITLE
[BUG]: `calc_realized_volatility()` returns error

### ISSUE THREAD

**Issue by jjfantini** [humblFINANCE/humblDATA#30]
## Tasks
- [ ] replace `rolling_std` with `rolling_std_by()`
## Notes
The `window_size` argument is trying to be coerced into a pystring. This is happening in `realized_volatility_helpers.py #123` in the `.rolling_std` polars function.

#### Bug
```
calc_realized_volatility(
            data=data7,
            window=window,
            method=rv_method,
            grouped_mean=rv_grouped_mean,
        )
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/jjfantini/github/humblFINANCE-org/humblDATA/src/humbldata/toolbox/technical/volatility/realized_volatility_model.py", line 152, in calc_realized_volatility
    out = func(**args_to_pass)
          ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jjfantini/github/humblFINANCE-org/humblDATA/src/humbldata/toolbox/technical/volatility/realized_volatility_helpers.py", line 123, in std
    pl.col(_column_name_returns).rolling_std(
  File "/Users/jjfantini/github/humblFINANCE-org/humblDATA/menv/lib/python3.11/site-packages/polars/_utils/unstable.py", line 59, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jjfantini/github/humblFINANCE-org/humblDATA/menv/lib/python3.11/site-packages/polars/expr/expr.py", line 9009, in rolling_std
    return self.rolling_std_by(
           ^^^^^^^^^^^^^^^^^^^^
  File "/Users/jjfantini/github/humblFINANCE-org/humblDATA/menv/lib/python3.11/site-packages/polars/_utils/unstable.py", line 59, in wrapper
    return function(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jjfantini/github/humblFINANCE-org/humblDATA/menv/lib/python3.11/site-packages/polars/expr/expr.py", line 7296, in rolling_std_by
    self._pyexpr.rolling_std_by(
TypeError: argument 'window_size': 'int' object cannot be converted to 'PyString'
```

**Comment by jjfantini** [comment]
closed with this commit: bb98559ebd8546edc95b6916490279acbbb36300
